package googlejam6.p190;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

/**
 * Google code jam problem solver.
 * Template generated by <a href="https://github.com/Faylixe/jammy">Jammy</a> plugin.
 * 
 * @author
 */
public final class RankandFileSolver {

	/** Scanner instance that allows to parse problem input. **/
	private final Scanner scanner;

	/**
	 * Default constructor.
	 * 
	 * @param scanner Scanner instance that allows to parse problem input. 
	 */
	private RankandFileSolver(final Scanner scanner) {
		this.scanner = scanner;
	}

	/**
	 * Solver entry point.
	 * 
	 * @param args Command line parameters.
	 * @throws FileNotFoundException If input file could not be parsed.
	 */
	public static void main(final String [] args) throws FileNotFoundException {
		final File file = new File(args[0]);
		final Scanner scanner = new Scanner(file);
		final int n = scanner.nextInt();
		final RankandFileSolver solver = new RankandFileSolver(scanner);
		for (int i = 0; i < n; i++) {
			System.out.print("Case #" + (i + 1) + ": ");
			int n1 = solver.scanner.nextInt();
			boolean[] m = new boolean[2501];
			for (int i3 = 1; i3 <= 2500; i3++) {
				m[i3] = false;
			}
			
			for (int i2 = 0; i2 < n1 * 2 - 1; i2++) {
				for (int j = 0; j < n1; j++) {
					int t = solver.scanner.nextInt();	
					m[t] = !m[t];
				}
			}
			
			boolean first = true;
			for (int i1 = 1; i1 <= 2500; i1++) {
				if (m[i1]) {
					if (first) {
						System.out.print(i1);
						first = false;
					} else {
						System.out.print(" " + i1);
					}
				}
			}
			System.out.println();
		}
		scanner.close();
	}

}